@host = http://localhost:3000

##### API AUTHORS ######
GET {{host}}/api/authors

###
GET {{host}}/api/authors/1

###
POST {{host}}/api/authors
Content-Type: application/json

{
    "name": "Lucia",
    "email": "lucia6@gmail.com",
    "image": "https://c.files.bbci.co.uk/48DD/production/_107435681_perro1.jpg"
}


##### API POSTS ######
GET {{host}}/api/posts

#####
GET {{host}}/api/posts/2

####
GET {{host}}/api/posts/authors/1

####
POST {{host}}/api/posts